### ISSUE TITLE
2.2.0 not available on PyPI

### ISSUE THREAD

**Issue by benjaminp** [ianare/exif-py#102]
1de2ee032b283188b54954f90d3d66c637f5142a is tagged as 2.2.0, but this version isn't available on PyPI, where the latest exifread release is 2.1.2.

**Comment by MortenHannemose** [comment]
This might be because the version in `exif-py/exifread/__init__.py` is still 2.1.2

**Comment by skorasaurus** [comment]
It was updated in https://github.com/ianare/exif-py/commit/02d5741a48e84203bb0df56420c2465e0874279d ; but the package maintainers will need to make a new package and upload it to pypi. 

I'm sure that they're probably just busy at the moment.

**Comment by vkotek** [comment]
Last package on PyPI is from 2015.. I'm experiencing 5 year old bugs :(

**Comment by bobalazek** [comment]
Any news on that one?

**Comment by simonw** [comment]
I'm interested in this release too - I want to extract EXIF data from HEIC files.

**Comment by ganego** [comment]
...

**Comment by hroskes** [comment]
I'd like to see v2.2.0 on pypi as well

**Comment by Cyb3r-Jak3** [comment]
For those who are still getting this issue, I have forked and published a version which is 2.2.0.

It is at https://pypi.org/project/ExifReader/

**Comment by hroskes** [comment]
@Cyb3r-Jak3 thank you!

**Comment by ianare** [comment]
Done! Sorry I had lost my access to Pypi ...

**Comment by benjaminp** [comment]
Thank you. I appreciate it.
