### ISSUE TITLE
Testing the library

### ISSUE THREAD

**Issue by rshk** [ianare/exif-py#11]
I recently forked the project here: https://github.com/rshk/exif-py/ and started some refactoring/clean up (pull requests coming soon), in order to make it installable from pypi and more efficient / maintainable.

I was wondering: what do you use for testing? Do you have a collection of jpegs along with known tag data? The library is seriously missing some unittests; I'd like to write some, but I miss the data..

**Comment by jayvdb** [comment]
@rshk , your fork still has lots of very good changes.  Do you plan on submitting them?  There are not significant changes here that conflict with your work.

**Comment by jayvdb** [comment]
I've got the sample exif tests running on a few extra platforms at https://build.opensuse.org/package/show/home:jayvdb:moban/python-ExifRead , using only #58 for Python 3 support, and everything is all green

**Comment by ianare** [comment]
Closing this. I want to be able to output to JSON for automated testing. Going the functional rather than unit route.
