### ISSUE TITLE
Choking on GPS IFD

### ISSUE THREAD

**Issue by bgreen-litl** [ianare/exif-py#45]
I'm using 1.4.2 but it also happens in 2.0 .

Here's the [image that causes the problem](https://farm9.staticflickr.com/8465/8411682640_f171a73d79_o.jpg).

DEBUG JPEG format recognized data[0:2]=0xFFD8
DEBUG data[2]=0xFF data[3]=0xE1 data[6:10]=Exif
DEBUG  Segment base 0x2
DEBUG   APP1 at base 0x2
DEBUG   Length: 0x17 0x7C
DEBUG   Code: Exif
DEBUG   Decrement base by 2 to get to pre-segment header (for compatibility with later code)
DEBUG Endian format is I (Intel)
DEBUG IFD 0 (Image) at offset 8:
DEBUG  ImageDescription: (0x010E) ASCII=Gran Turismo 5 @ 170
DEBUG  Make: (0x010F) ASCII=Polyphony Digital Inc. @ 186
DEBUG  Model: (0x0110) ASCII=Gran Turismo 5 @ 210
DEBUG  Orientation: (0x0112) Short=Horizontal (normal) @ 54
DEBUG  XResolution: (0x011A) Ratio=72 @ 226
DEBUG  YResolution: (0x011B) Ratio=72 @ 234
DEBUG  ResolutionUnit: (0x0128) Short=Pixels/Inch @ 90
DEBUG  Software: (0x0131) ASCII=PMB Service Uploader @ 242
DEBUG  DateTime: (0x0132) ASCII=2012:06:23 08:24:05 @ 264
DEBUG  YCbCrPositioning: (0x0213) Short=Co-sited @ 126
DEBUG  Copyright: (0x8298) ASCII=TM&Copyright (C) 20, ... ] @ 284
DEBUG  ExifOffset: (0x8769) Long=340 @ 150
Traceback (most recent call last):
  File "./EXIF.py", line 131, in <module>
    main()
  File "./EXIF.py", line 99, in main
    data = process_file(img_file, stop_tag=stop_tag, details=detailed, strict=strict, debug=debug)
  File "/Users/bob/src/exif-py/exifread/__init__.py", line 204, in process_file
    hdr.dump_ifd(ifd, ifd_name, stop_tag=stop_tag)
  File "/Users/bob/src/exif-py/exifread/classes.py", line 238, in dump_ifd
    logger.debug('%s SubIFD at offset %d:', ifd_info[0], values[0])
IndexError: list index out of range

**Comment by javierpra** [comment]
@bgreen-litl Thanks.  Someone will have a look as soon as we can.

**Comment by ianare** [comment]
Can you test with the latest version from Git please?

If it's OK then I will publish a new version with this fix.

Thanks,

- ianaré

**Comment by bgreen-litl** [comment]
Thanks! Your fix appears to fix the issue, but I need to work through some issues that the current master introduces to my dependent code.  I was previously using 1.4.2 and it seems some tag names in the returned dict have changed in 2.x e.g. "GPS GPSLongitude" -> "EXIF GPS GPSLongitude"  Also, I filed #46 which for the time being prevents me from switching off of 1.4.x.
