### ISSUE TITLE
Error on unicode metadata

### ISSUE THREAD

**Issue by sim1camporeale** [ianare/exif-py#57]
I found an exception. This line:

```
printable = str(values[0:20])[0:-1] + ", ... ]"
```

throws an exception when the string contains unicode characters. I fixed this issue on my branch. I'll send you a pull request.

**Comment by SoerenWeber** [comment]
I just ran into this exception; thanks for fixing it, @sim1camporeale ! 
I'd like to update to the bugfixed version via PyPi but the last release isn't current enough. Could you make a new release please, @ianare ?
