### ISSUE TITLE
EXIF output format? 

### ISSUE THREAD

**Issue by dbrb2** [ianare/exif-py#62]
I don't this is a bug, but I wonder if you can explain the below....

All the EXIF tags I read are returned in formformat: 

'<tag name>': <hex_number> <type>=<value> @ <number>
For instance: 

'Image Copyright': (0x8298) ASCII=Transport for London @ 188

Can you explain what the hex and the @ <number> fields are for? I can parse them out - but just interested...

**Comment by sybrenstuvel** [comment]
They are objects of type `exifread.classes.IfdTag`. The information you see is defined in [classes.py](https://github.com/ianare/exif-py/blob/develop/exifread/classes.py).
