### ISSUE TITLE
webp support

### ISSUE THREAD

**Issue by andrewharvey** [ianare/exif-py#71]
`cwebp -metadata all -q 80 image.jpg -o image.webp` will retain EXIF information in WebP files converted from JPEG however exif-py doesn't seem able to read:

```
> ./EXIF.py image.webp
Opening: i.webp
No EXIF information found
```

**Comment by grucin** [comment]
I've added webp support in https://github.com/ianare/exif-py/pull/116

**Comment by ianare** [comment]
Closing, thanks much!
