### ISSUE TITLE
Cannot seem to read EXIF data from PNGs

### ISSUE THREAD

**Issue by podollb** [ianare/exif-py#78]
Seems as though it cannot read EXIF data from PNGs

```
$ EXIF.py --debug /tmp/1375-1.png
INFO   Opening: /tmp/1375-1.png
DEBUG  File format not recognized.
WARNING No EXIF information found
```

With other EXIF viewing/editing tools I can see the EXIF data in the PNG referenced above.

**Comment by robputt796** [comment]
Hi @podolib

Unfortunately PNGs do not store EXIF data. They do allow storing meta data but it is not in true EXIF format it is some other weird hackery. Only JPEGs and TIFF images officially support EXIF.  @ianare  I think this one can be closed.

Best Regards,

Rob
