### ISSUE TITLE
exifread supports not panasonic's RW2 files

### ISSUE THREAD

**Issue by wilmarusb** [ianare/exif-py#79]
The panasonic RW2 file begins with 'IIU\x00' and not with 'II*\x00' or 'MM\x00'.
line 30,31,32 of init.py in directory exifread are:
30 # determine whether it's a JPEG or TIFF
31 data = f.read(12)
32 if data[0:4] in [b'II*\x00', b'MM\x00*']:
if you change line 32 to:
if data[0:4] in [b'II*\x00', b'MM\x00*', b'IIU\x00']:
exifread runs also with Panasonic's RW2

**Comment by westscz** [comment]
With line 32 changed to:

`if data[0:2] in [b'II', b'MM']:`

everything for panasonic RW2 files work correctly. 
We can close this issue

**Comment by austinbutler** [comment]
It seems this is solved by https://github.com/ianare/exif-py/pull/91 which is merged but not yet released.

**Comment by austinbutler** [comment]
This issue should be closed, fix was released in 2.2.0.
