### ISSUE TITLE
Please re-enable Travis

### ISSUE THREAD

**Issue by robputt796** [ianare/exif-py#81]
Hi @ianare 

Please can you re-enable Travis for this repository? 

Also is the repo still actively maintained, if not please can we discuss maybe someone else taking over maintenance of the repo moving forward as it is a Python module we love using.

Best Regards,

Rob

**Comment by chrstphrchvz** [comment]
There has been some activity recently. It looks like Travis is working now, too: https://travis-ci.org/ianare/exif-py

**Comment by ianare** [comment]
Sorry for the delay. Travis has been re-enabled.

It's true that I have not been very active myself on this project, however I'll do my best to merge any pull requests. If you've made some improvements to the lib, don't hesitate to send them this way :-)

Thanks!
