### ISSUE TITLE
Read error in Pyhthon 3, not present in Python 2

### ISSUE THREAD

**Issue by frankrolf** [ianare/exif-py#87]
I am using `exifread` as a Python module to create track logs from a given folder of photos.
The following error comes up running  exifread 2.1.2 on Python 3.7.1 (which is not an issue in Python 2.7.15): 

```
2005-12-14_143947.jpg
Possibly corrupted field Tag 0x0000 in MakerNote IFD
Traceback (most recent call last):
  File "pics_to_gpx.py", line 125, in <module>
    tags = exifread.process_file(ph)
  File "/usr/local/lib/python3.7/site-packages/exifread/__init__.py", line 216, in process_file
    hdr.decode_maker_note()
  File "/usr/local/lib/python3.7/site-packages/exifread/classes.py", line 399, in decode_maker_note
    tag_dict=makernote.nikon.TAGS_NEW, relative=1)
  File "/usr/local/lib/python3.7/site-packages/exifread/classes.py", line 186, in dump_ifd
    values = self.file.read(count)
OSError: [Errno 22] Invalid argument
```

The camera in question was a Nikon D70s, attached are two sample images that trigger the error.
Thanks for looking into it!

![2005-12-14_142546](https://user-images.githubusercontent.com/2049645/50042757-32c6d100-0068-11e9-9c7f-d95efed1b739.jpg)
![2005-12-14_143947](https://user-images.githubusercontent.com/2049645/50042758-335f6780-0068-11e9-90cc-f41c9ddfbfde.jpg)

**Comment by ianare** [comment]
Thanks for the report. Can I add these images to the test repo? They would be released under the "Attribution-ShareAlike 4.0 International" license.

**Comment by frankrolf** [comment]
That’s no problem!
You may add those images to the repo.

**Comment by ianare** [comment]
Bug has been fixed in latest version, although there are some unreadable makernote tags.
