### ISSUE TITLE
Python 3.6+ support?

### ISSUE THREAD

**Issue by chrstphrchvz** [ianare/exif-py#88]
Is this project ready/willing to support Python 3.6 and 3.7?

I do not yet notice any issues specifically due to running either EXIF.py 2.1.2 or the develop branch on Python 3.7.2. Note that package managers such as those for Ubuntu and Fedora have already gone ahead with using their `python3-exif` packages on Python 3.6/3.7.

**Comment by r7l** [comment]
Any chance to get Python 3.6 support in this project?

**Comment by mtoftum** [comment]
The description page just lists what's (was) being tested.
Exif.py seems to work perfectly fine with Python 3.7.

**Comment by ianare** [comment]
Sorry for the wait, Python 3.6 and 3.7 are now officially supported (tests added) in the develop branch, although the master branch and version 2.1.2 should work.
