### ISSUE TITLE
py3exiv2 not reading all the tags in a TIFF stack

### ISSUE THREAD

**Issue by devangel77b** [ianare/exif-py#94]
1. When I use py3exiv2 to try to open and read tags from a tiff stack created by a FLIR camera, it only reads up to tags for the 3rd image in the stack. For the image I am testing I get 108 exif keys. 

2. When I open the same image with exifread in Python 2 I get tags for around 700 images which is what I expect to see in pyexiv2. For the image I am testing I get 16086 keys, including ones that look like they are for each image in the stack ('IFD 765 Resolution Unit' for example). 

I'd rather use pyexiv2 because I plan to break the images into separate ones for processing and want to preserve the tags in the individual images and when I process the stack. exifread is not able to write keys.

**Comment by ianare** [comment]
I'm sorry but there are no plans to add write support to ExifRead.
