### ISSUE TITLE
2.2.0 changelog suggestion

### ISSUE THREAD

**Issue by chrstphrchvz** [ianare/exif-py#97]
https://github.com/ianare/exif-py/blob/b69af85a7f52578bd17f8c93cafd4248511558ab/ChangeLog.rst#L9

I suggest this change either instead or at least additionally reflect the original contributions, something like
- "Refactor to use Python's struct module for packing/unpacking" credited to Dave Jones (waveform80), and
- "Support floating point fields" credited to Reed Nightingale (reedbn).

**Comment by ianare** [comment]
Done, only a year late :-(
